# Header
menu:
#  Archives: /archives
  Blog: /blog
  Home: /

# Read More text
excerpt_link: Read More

# Widgets List
widgets:
  about: My name is Daniel Bidulock. I am a computer programmer and Wycliffe Bible Translator. I cultivate biblical and computer literacy around the world.
  tags: true
