# Header
menu:
  Home: /
  Archives: /archives
  Blog: /blog

# Read More text
excerpt_link: Read More

# Widgets List
widgets:
  about: My name is Daniel Bidulock. I am a Wycliffe Bible Translator. This is my blog.
  tags: true
